services:
  foodtrax:
    build: .
    # image: localhost:5000/foodtrax:latest
    container_name: Foodtrax
    restart: unless-stopped
    networks:
      - virtual-network
    labels:
      dmz.url: http://foodtrax.docker.local/
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

networks:
  virtual-network:
    external: true
    name: virtual-network